name: Build and Release Apps

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Apps

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        include:
          - os: macos-latest
            TARGET: 'macos'

#          - os: ubuntu-latest
#            TARGET: 'linux'
    runs-on: ${{ matrix.os }}

    env:
      APP_VERSION: release_$(date +'%Y-%m-%d_%H-%m-%S')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "master"
      - name: Install pub Dependencies
        run: flutter pub get

      - name: Configure
        run: flutter config --enable-${{ matrix.TARGET }}-desktop

      - name: build
        run: flutter build ${{ matrix.TARGET }}

      - name: Release Apps
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.APP_VERSION }}
          name: ${{ env.APP_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "build/app/outputs/apk/release/*.apk,build/ios/iphoneos/app.ipa,build/macos/Products/Release/sshstudio"
